FROM python:3.9-alpine
WORKDIR /app
COPY requirements.txt .
# FIX: Added --no-cache-dir to satisfy Super-Linter/Hadolint
RUN pip install --no-cache-dir -r requirements.txt 
COPY . .
CMD ["python", "app.py"]