version: '3.8'

services:
  # --- db ---
  db_container:  # ='host' dans app.py
    build: 
      context: .
      dockerfile: Dockerfile_db
    container_name: db_container
    restart: always
    volumes:
      - sauvegarde_db_compose:/var/lib/postgresql/data

  # --- web ---
  web_container:
    build: 
      context: .
      dockerfile: Dockerfile_web
    container_name: web_container
    ports:
      - "5000:5000"  
    depends_on:
      - db_container  # Attend que la db démarre avant de se lancer

# --- définition volume persistant ---
volumes:
  sauvegarde_db_compose: